<?php
/**
 * A Magento 2 module named Dealer4Dealer\SubstituteOrders
 * Copyright (C) 2017 Maikel Martens
 *
 * This file is part of Dealer4Dealer\SubstituteOrders.
 *
 * Dealer4Dealer\SubstituteOrders is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * @codingStandardsIgnoreFile
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
    $_item = $block->getItem();
    $_currencyHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>

<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item['orderitem_id'] ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item['name']) ?></strong>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ echo $_item['sku'] ?>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $_currencyHelper->currency($_item['price'], true, false); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $_item['qty']*1 ?></span>
            </li>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $_currencyHelper->currency($_item['row_total'], true, false); ?>
    </td>
</tr>
