<?php
/**
 * A Magento 2 module named Dealer4Dealer\SubstituteOrders
 * Copyright (C) 2017 Maikel Martens
 *
 * This file is part of Dealer4Dealer\SubstituteOrders.
 *
 * Dealer4Dealer\SubstituteOrders is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * @codingStandardsIgnoreFile
 */

/** @var  $block \Magento\Sales\Block\Order\Track */
?>

<?php $shipments = $block->getOrder()->getShipmentCollection(); ?>

<?php foreach ($shipments as $shipment) : ?>
    <?php foreach ($shipment->getTracking() as $tracking) : ?>
        <div class="page tracking">
            <h2 class="subtitle"><?php /* @noEscape */ echo $block->escapeHtml(__('Tracking code #%1', $tracking->code)); ?></h2>
            <div class="tracking-info">
                <p>
                    <strong><?php /* @noEscape */ echo $block->escapeHtml(__('Carrier: ')); ?></strong><?php echo $tracking->name; ?> </br>
                    <strong><?php /* @noEscape */ echo $block->escapeHtml(__('Tracking link: ')); ?></strong><?php echo $tracking->url; ?>
                </p>
            </div>
            <div class="actions">
                <button type="button"
                        title="<?php echo $block->escapeHtml(__('Close Window')); ?>"
                        class="action close"
                        onclick="window.close(); window.opener.focus();">
                    <span><?php echo $block->escapeHtml(__('Close Window')); ?></span>
                </button>
            </div>
        </div>
    <?php endforeach; ?>
<?php endforeach; ?>
