<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Dealer4Dealer\SubstituteOrders\Block\Order\Invoice\Items */

?>
<?php
$_order = $block->getOrder();
?>
<div class="actions-toolbar">
    <!-- TODO print all invoices -->
    <!--    <a href="--><?php ///* @escapeNotVerified */ echo $block->getPrintAllInvoicesUrl($_order) ?><!--"-->
    <!--       target="_blank"-->
    <!--       class="action print">-->
    <!--        <span>--><?php ///* @escapeNotVerified */ echo __('Print All Invoices') ?><!--</span>-->
    <!--    </a>-->
</div>

<?php if(count($_order->getInvoices()) > 0): ?>
    <?php foreach ($_order->getInvoices() as $_invoice): ?>
        <div class="order-title">
            <strong><?php /* @escapeNotVerified */
                echo __('Invoice #') ?><?php /* @escapeNotVerified */
                echo $_invoice->getInvoiceId(); ?></strong>
            <a href="<?php /* @escapeNotVerified */
            echo $block->getPrintInvoiceUrl($_invoice) ?>"
               onclick="this.target='_blank'"
               class="action print">
                <span><?php /* @escapeNotVerified */
                    echo __('Print Invoice') ?></span>
            </a>
        </div>
        <div class="table-wrapper table-order-items invoice">
            <table class="data table table-order-items invoice" id="my-invoice-table-<?php /* @escapeNotVerified */
            echo $_invoice->getId(); ?>">
                <caption class="table-caption"><?php /* @escapeNotVerified */
                    echo __('Items Invoiced') ?></caption>
                <thead>
                <tr>
                    <th class="col name"><?php /* @escapeNotVerified */
                        echo __('Product Name') ?></th>
                    <th class="col sku"><?php /* @escapeNotVerified */
                        echo __('SKU') ?></th>
                    <th class="col price"><?php /* @escapeNotVerified */
                        echo __('Price') ?></th>
                    <th class="col qty"><?php /* @escapeNotVerified */
                        echo __('Qty Invoiced') ?></th>
                    <th class="col subtotal"><?php /* @escapeNotVerified */
                        echo __('Subtotal') ?></th>
                </tr>
                </thead>
                <?php $_items = $_invoice->getAllItems(); ?>
                <?php $_count = count($_items) ?>
                <?php foreach ($_items as $_item): ?>
                    <tbody>
                    <?php if ($itemRenderBlock = $block->getChildBlock('renderer.list')): ?>
                        <?php $itemRenderBlock->setData('item', $_item) ?>
                        <?php echo $block->getChildHtml('renderer.list', false); ?>
                    <?php endif; ?>
                    </tbody>
                <?php endforeach; ?>
                <tfoot>
                <?php echo $block->getInvoiceTotalsHtml($_invoice) ?>
                </tfoot>
            </table>
        </div>
        <!-- TODO implement invoice comments -->
        <?php //echo $block->getInvoiceCommentsHtml($_invoice)?>
        <?php echo $block->getInvoiceAttachmentHtml($_invoice)?>
    <?php endforeach; ?>
<?php else: ?>
    <p><?php /* @escapeNotVerified */
        echo __('No invoices available for this order.') ?></p>
<?php endif; ?>
